[build]
  command = "pip install -r requirements.txt"
  publish = "static"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
