[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.11"

[build.env]
NIXPACKS_NIXPKGS = "wget" 